# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# for debugging
#set -o errexit
#set -o xtrace

# general config for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_general.sh ] && source ~/.ciber_dotfiles/shell/bashrc_general.sh

# exports config for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_exports.sh ] && source ~/.ciber_dotfiles/shell/bashrc_exports.sh

# alias for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_alias.sh ] && source ~/.ciber_dotfiles/shell/bashrc_alias.sh

# tmux for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_tmux.sh ] && source ~/.ciber_dotfiles/shell/bashrc_tmux.sh

# man for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_man.sh ] && source ~/.ciber_dotfiles/shell/bashrc_man.sh

# extra customizations for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc-extra.sh ] && source ~/.ciber_dotfiles/shell/bashrc-extra.sh