# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# for debugging
#set -o errexit
#set -o xtrace

# language
export LC_ALL=es_ES.UTF-8
export LANG=es_ES.UTF-8

# general config for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_general.sh ] && . ~/.ciber_dotfiles/shell/bashrc_general.sh

# alias for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_alias.sh ] && . ~/.ciber_dotfiles/shell/bashrc_alias.sh

# tmux for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_tmux.sh ] && . ~/.ciber_dotfiles/shell/bashrc_tmux.sh

# man for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc_man.sh ] && . ~/.ciber_dotfiles/shell/bashrc_man.sh

# extra customizations for bashrc
[ -f ~/.ciber_dotfiles/shell/bashrc-extra.sh ] && . ~/.ciber_dotfiles/shell/bashrc-extra.sh