#!/usr/bin/env bash

## SHELL
bash=true
bash_general=true
bash_exports=false
bash_alias=false

bash_tmux=false
bash_prompt=false

wget=false
screen=false
curl=false

editorconfig=false

## TMUX
tmux=false

## VIM
vim=false

## GIT
git=false

